### ISSUE TITLE
Crash on iOS 16 and xcode 14 when connecting to stringee server - iOS 16 with XCode 14 no longer support VOIP socket

### ISSUE THREAD

**Issue by phanbaohuy96** [stringeecom/stringee_flutter_plugin#6]
The following message comes from XCode 14 on iOS 16 iPhone

libsp.dylib`spd_checkin_socket.cold.1:
    0x1f25f8364 <+0>:  adrp   x8, 141905
    0x1f25f8368 <+4>:  adrp   x9, 0
    0x1f25f836c <+8>:  add    x9, x9, #0xa3f            ; "Linked against modern SDK, VOIP socket will not wake. Use Local Push Connectivity instead"
    0x1f25f8370 <+12>: str    x9, [x8, #0x400]
->  0x1f25f8374 <+16>: brk    #0x1

**Comment by HiepH-Stringee** [comment]
<img width="681" alt="Screen Shot 2022-10-15 at 21 18 54" src="https://user-images.githubusercontent.com/109797881/195991395-bdda724d-f2e2-406d-9915-9dfa25aa94b5.png">
this bug will fix in next version, for hot fix remove version of Stringee on file podspec
